### ISSUE TITLE
[FEAT] Enable specifying models path via UI, possibly model map

### ISSUE THREAD

**Issue by kfsone** [ParisNeo/lollms-webui#453]
I'm exploring various LM hosting options (ollama, ooba webui, lm studio, lollms, koboldcpp, etc) and for the most part I'm able to have them all share models in a single folder (/opt/ai/models and e:/models) but I end up having to fiddle with symlinks for LM Studio and Lollms. For ollama I just run it in a docker container and bindmount the models folder for it.

It would be great if the huggingface binding, at least, could take a path to the models directory, if not Elf. Even then, it seems like broader support might call for the introduction of a reasonably simple "modelmap.yaml" type file which lets you (at least) specify the user-facing model name, the model file or dir

```
- mistral-7b-instruct:
  - presents-as: Mistral-7B-Instruct-v0.1
  - folder: /opt/ai/models/TheBloke/Mistral-7B-Instruct-v01-GGUF  # optional
  - files:
    - tag: Q5_K_M
    - file: mistral-7b-instruct-v0.1.Q5_K_M.gguf

- claude2:
  - file: /opt/ai/models/TheBloke/claude2-alpaca-13B-GGUF/claude2-alpaca-13b.Q5_K_M.gguf
```
